# Generated by Django 3.2.12 on 2022-04-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calorie', models.IntegerField(max_length=100)),
                ('protein', models.IntegerField(max_length=100)),
                ('fat', models.IntegerField(max_length=100)),
                ('carbohydrates', models.IntegerField(max_length=100)),
                ('dietary_fiber', models.IntegerField(max_length=100)),
            ],
        ),
    ]
