# Generated by Django 3.2.12 on 2022-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220415_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dietary_fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
