# Generated by Django 3.2.12 on 2022-04-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_cook'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
