# Generated by Django 3.2.12 on 2022-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='pick',
            field=models.BooleanField(default=False),
        ),
    ]
